// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADaTxWHemBI9QN8C3wai4ffwpiLG6gAlo',
    appId: '1:410107154802:web:95c2cfb0831ae1d25a0deb',
    messagingSenderId: '410107154802',
    projectId: 'moodora-app-4d42e',
    authDomain: 'moodora-app-4d42e.firebaseapp.com',
    storageBucket: 'moodora-app-4d42e.firebasestorage.app',
    measurementId: 'G-5YK3VG3F20',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDr--4mXQcM6lgcZI2gcXs-pNunL117Xr4',
    appId: '1:410107154802:android:a228dc6641d509da5a0deb',
    messagingSenderId: '410107154802',
    projectId: 'moodora-app-4d42e',
    storageBucket: 'moodora-app-4d42e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAuGN3sW0vuAcKf7IjLUbqOtku_Pt28C_s',
    appId: '1:410107154802:ios:4c1572aa344fd94c5a0deb',
    messagingSenderId: '410107154802',
    projectId: 'moodora-app-4d42e',
    storageBucket: 'moodora-app-4d42e.firebasestorage.app',
    iosBundleId: 'com.example.moodJournal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAuGN3sW0vuAcKf7IjLUbqOtku_Pt28C_s',
    appId: '1:410107154802:ios:4c1572aa344fd94c5a0deb',
    messagingSenderId: '410107154802',
    projectId: 'moodora-app-4d42e',
    storageBucket: 'moodora-app-4d42e.firebasestorage.app',
    iosBundleId: 'com.example.moodJournal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyADaTxWHemBI9QN8C3wai4ffwpiLG6gAlo',
    appId: '1:410107154802:web:d3d1e2cdba6123af5a0deb',
    messagingSenderId: '410107154802',
    projectId: 'moodora-app-4d42e',
    authDomain: 'moodora-app-4d42e.firebaseapp.com',
    storageBucket: 'moodora-app-4d42e.firebasestorage.app',
    measurementId: 'G-C3C20YB3EK',
  );
}
